### ISSUE TITLE
When the storyshots config does not exist, the test fails

### ISSUE THREAD

**Issue by Auroratide** [compoze-labs/storyshots#4]
When the storyshots config does not exist, the test fails.

```
Running 0 tests using 0 workers
Error: EISDIR: illegal operation on a directory, read

   at storyshots.env.ts:26

  24 |     const storyshotsConfigPath = '/storyshots/.storyshots.json'
  25 |     if (fs.existsSync(storyshotsConfigPath)) {
> 26 |         const storyshotsConfig = JSON.parse(fs.readFileSync(storyshotsConfigPath, 'utf8')) as StoryshotsConfig
     |                                                ^
  27 |         if (storyshotsConfig.ignoreStories) {
  28 |             env.ignoreStories = storyshotsConfig.ignoreStories.map(StorybookStory.fromString)
  29 |         }

    at storyshotsEnv (/storyshots/storyshots.env.ts:26:48)
    at Object.<anonymous> (/storyshots/storyshots.testStories.ts:5:53)
    at Object.<anonymous> (/storyshots/storyshots.spec.ts:2:1
```

**Comment by Auroratide** [comment]
I believe this is the issue: https://github.com/moby/moby/issues/21612
